  version: '3.8'

  services:
    app:
      image: alekseyvashchenko/t1_task_3:latest
      ports:
        - "8080:8080"
      depends_on:
        - db
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
        SPRING_DATASOURCE_USERNAME: test
        SPRING_DATASOURCE_PASSWORD: test
      networks:
        - app-network

    db:
      image: postgres:15
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
      ports:
        - "5433:5432"
      networks:
        - app-network
  networks:
    app-network:
      driver: bridge
